routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// 需要登录
// 这里部分用数组的写法,因为,数组的写法比@的写法有个好处是,ide可以识别到,可以点击直接跳转到对应方法
Route::middleware('auth')->group(
    function () {
        // 权限相关
//        Route::get('/per/create', [\App\Http\Controllers\PermissionController::class, 'create']);
//        Route::get('/per/index', [\App\Http\Controllers\PermissionController::class, 'index']);
        // 初始化
        Route::get('/init', [\App\Http\Controllers\InitController::class, 'systemInit'])->name('init');
        Route::get('/clear', [\App\Http\Controllers\InitController::class, 'clear'])->name('clear');
        //首页
        Route::get('/', [\App\Http\Controllers\IndexController::class, 'index'])->name('index');
        Route::get('/welcome', [\App\Http\Controllers\IndexController::class, 'welcome'])->name('welcome');
        Route::get('/logout', [\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');

        // 个人信息
        Route::get('/info', [\App\Http\Controllers\UserController::class, 'info'])->name('user.info');
        // 学生
        Route::resource('/user', 'UserController');
        Route::post('/getuser', 'UserController@getUser')->name('getuser');
        Route::delete('/delall', 'UserController@deleteAll')->name('user.delall');
        Route::delete('/delparent/{id}', 'UserController@delParent')->name('user.delparent');
        Route::get('/export/user', 'UserController@export')->name('user.export');
        // 老师
        Route::resource('/teacher', 'TeacherController');
        Route::post('/getteacher', 'TeacherController@getTeacher')->name('getteacher');

        // 修改密码
        Route::get('/repwd', 'LoginController@showRepwdForm')->name('repwd');
        Route::post('/repwd', 'LoginController@repwd')->name('dorepwd');

        // 课程
        Route::resource('/course', 'CoursesController');
        Route::post('/getcourse', 'CoursesController@getcourse')->name('getcourse');

        // 考试
        Route::resource('/exam', 'ExamsController');
        Route::post('/getexams', 'ExamsController@getexams')->name('getexams');

        // 成绩
        Route::resource('/score', 'ScoresController');
        Route::post('/getscore', 'ScoresController@getscore')->name('getscore');
        Route::get('/export/score', 'ScoresController@export')->name('score.export');
        Route::post('/getfull', 'ScoresController@getFull')->name('score.getfull');

        // 成绩分析
        Route::get('/analyze/index', 'ScoreAnalyzeController@index')->name('analyze.index');
        Route::get('/analyze/pie/{cid}/{eid}', 'ScoreAnalyzeController@getPie')->name('analyze.getpie');
        Route::post('/analyze/showall', 'ScoreAnalyzeController@showAll')->name('analyze.showall');
        Route::post('/analyze/tips', 'ScoreAnalyzeController@tips')->name('analyze.tips');
        // 获取个人成绩不同考试折线图
        Route::post('/analyze/getrank', 'ScoreAnalyzeController@getRank')->name('analyze.getrank');
        // 个人分析列表页
        Route::get('/analyze/gerenfx', 'ScoreAnalyzeController@gerenfx')->name('analyze.gerenfx');
        Route::post('/analyze/hasscore', 'ScoreAnalyzeController@getHasScoreUser')->name('analyze.hasscore');

        // 管理员专属
        Route::resource('/admin', 'AdminController');
        Route::post('/admin.data', 'AdminController@getData')->name('admin.data');
    }
);


// 不需要登录
Route::middleware('guest')->group(
    function () {
        Route::get('/login', 'LoginController@index')->name('login');
        Route::post('/dologin', 'LoginController@store')->name('login.store');
    }
);

Route::any('/test', 'TestController@test')->name('test');

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Models\TeachersModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class TeacherController extends Controller
{

    public function index()
    {
        return view('teachers.index');
    }

    public function getTeacher(Request $request)
    {
        $page = $request->input('page');
        $limit = $request->input('limit');
        $offset = ($page - 1) * $limit;
        $data = TeachersModel::offset($offset)->paginate($limit)->toArray();
        $res['data'] = $data['data'];
        $res['code'] = 0;
        $res['count'] = $data['total'];
        $res['msg'] = '获取数据失败';

        return $res;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('teachers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $res = TeachersModel::create($input);
        if ($res) {
            return $this->success('添加成功');
        } else {
            return $this->fail('添加失败');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $teacher = TeachersModel::find($id);

        return view('teachers.show', compact('teacher'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $teacher = TeachersModel::find($id);
        if (Gate::denies('isAdmin')) {
            return view('user.noper');
        }

        return view('teachers.edit', compact('teacher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, $id)
    {
        $teacher = TeachersModel::find($id);

        if (Gate::denies('isAdmin')) {
            return $this->fail('您无权修改老师');
        }
        $res = $teacher->update($request->all());
        if ($res) {
            return $this->success('修改成功');
        } else {
            return $this->fail('修改失败');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Request $request, $id)
    {
        if (Gate::denies('isAdmin')) {
            return $this->fail('您无权删除老师');
        }
        $res = TeachersModel::destroy($id);
        if ($res) {
            return $this->success('删除成功');
        }

        return $this->fail('删除失败');
    }
}

resources/views/teachers/create.blade.php
@extends('common.layout')

@section('content')
    <form class="layui-form layuimini-form">
        <div class="layui-form-item">
            <label class="layui-form-label required">老师名称</label>
            <div class="layui-input-inline">
                <input type="text" lay-verify="required" name="name" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label required">性别</label>
            <div class="layui-input-inline">
                <input type="radio" name="sex" value="男" title="男" checked>
                <input type="radio" name="sex" value="女" title="女">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">联系电话</label>
            <div class="layui-input-inline">
                <input type="text" name="phone" lay-verify="required" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">QQ</label>
            <div class="layui-input-inline">
                <input type="text" name="qq" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item" style="text-align: center;">
            <button class="layui-btn" lay-filter="save" lay-submit="">提交</button>
        </div>
    </form>
@stop

@section('js')
    <script>
        layui.use(['form', 'layer'],
            function () {
                var $ = layui.jquery,
                    form = layui.form,
                    layer = layui.layer;

                //监听提交
                form.on('submit(save)',
                    function (data) {
                        $.post('{{route('teacher.store')}}', data.field, function (res) {
                            my.msg(res);
                        });
                        return false;
                    });
            });
    </script>
@stop

resources/views/teachers/edit.blade.php
@extends('common.layout')

@section('content')
    <form class="layui-form layuimini-form" lay-filter="teacher">
        <div class="layui-form-item">
            <label class="layui-form-label required">老师名称</label>
            <div class="layui-input-inline">
                <input type="text" lay-verify="required" name="name" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label required">性别</label>
            <div class="layui-input-inline">
                <input type="radio" name="sex" value="男" title="男">
                <input type="radio" name="sex" value="女" title="女">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">联系电话</label>
            <div class="layui-input-inline">
                <input type="text" name="phone" class="layui-input" value="{{$teacher->phone}}">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">QQ</label>
            <div class="layui-input-inline">
                <input type="text" name="qq" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item" style="text-align: center;">
            <button class="layui-btn" lay-filter="save" lay-submit="">提交</button>
        </div>
    </form>
@stop

@section('js')
    <script>
        layui.use(['form', 'layer'],
            function () {
                var $ = layui.jquery,
                    form = layui.form,
                    layer = layui.layer;

                //给表单赋值
                form.val("teacher", @json($teacher));

                //监听提交
                form.on('submit(save)',
                    function (data) {
                        $.ajax({
                            type: 'put',
                            url: '{{route('teacher.update',$teacher->id)}}',
                            data: data.field,
                            success: function (res) {
                                my.msg(res);
                            }
                        });
                        return false;
                    });
            });
    </script>
@stop

resources/views/teachers/index.blade.php
@extends('common.layout')

@section('content')
    <table id="user_table" lay-filter="test"></table>
@stop

@section('js')
    @include('common.addbtn',['name'=>'添加'])
    @include('common.operation')

    <script>
        layui.use(['laydate', 'table'],
            function () {
                var $ = layui.jquery,
                    laydate = layui.laydate
                    , table = layui.table;
                //执行一个laydate实例
                laydate.render({
                    elem: '#start' //指定元素
                    , trigger: 'click'
                });

                //执行一个laydate实例
                laydate.render({
                    elem: '#end' //指定元素
                    , trigger: 'click'
                });
                table.render({
                    elem: '#user_table'
                    , height: 'full-130'
                    , method: 'post'
                    , url: '{{route('getteacher')}}' //数据接口
                    , page: true //开启分页
                    , cellMinWidth: 50 //全局定义常规单元格的最小宽度
                    , cols: [[ //表头
                        {type: 'numbers', title: '序号', width: 100, align: 'center'}
                        , {field: 'name', title: '姓名', sort: true, align: 'center'}
                        , {field: 'sex', title: '性别', sort: true, align: 'center'}
                        , {field: 'phone', title: '电话', sort: true, align: 'center'}
                        , {field: 'qq', title: 'QQ', sort: true, align: 'center'}
                        @can('isAdmin')
                        , {title: '操作', toolbar: '#barDemo', width: 150}
                        @endcan
                    ]]
                    , limit: 10
                    , limits: [10, 20, 30, 50, 100]
                    , toolbar: '#toolbarDemo'
                    , defaultToolbar: ['filter', 'print', 'exports']
                });

                @can('isAdmin')
                //监听行双击事件（双击事件为：row）
                table.on('rowDouble(test)', function (obj) {
                    var data = obj.data;
                    // 在这里显示某个学生具体的弹窗
                    var url = '{{route('teacher.edit','xxx')}}'.replace('xxx', data.id);
                    my.open('编辑<span style="color:red;">' + data.name + '</span>老师信息', url, 40, 60);
                    //标注选中样式
                    obj.tr.addClass('layui-table-click').siblings().removeClass('layui-table-click');
                });
                @endcan

                //头工具栏事件
                table.on('toolbar(test)', function (obj) {
                    switch (obj.event) {
                        case 'add':
                            my.open('添加老师', '{{route('teacher.create')}}', 40);
                            break;
                    }
                });
                //监听行工具事件
                table.on('tool(test)', function (obj) {
                    var data = obj.data;
                    if (obj.event === 'del') {
                        layer.confirm('真的删除<span style="color:red;">' + data.name + '</span>老师么', function (index) {
                            var url = '{{route('teacher.destroy','xxx')}}'.replace('xxx', data.id);
                            $.ajax({
                                type: 'delete',
                                url: url,
                                success: function (res) {
                                    my.msg(res);
                                }
                            });
                        });
                    } else if (obj.event === 'edit') {
                        var url = '{{route('teacher.edit','xxx')}}'.replace('xxx', data.id);
                        my.open('编辑<span style="color:red;">' + data.name + '</span>老师信息', url);
                    }
                });
            });
    </script>
@stop

resources/views/teachers/show.blade.php
@extends('common.layout')

@section('content')
    <table class="layui-table">
        <tr>
            <td>授课老师</td>
            <td>{{$teacher->name}}</td>
        </tr>
        <tr>
            <td>性别</td>
            <td>{{$teacher->sex}}</td>
        </tr>
        <tr>
            <td>联系电话</td>
            <td>{{$teacher->phone}}</td>
        </tr>
        <tr>
            <td>QQ</td>
            <td>{{$teacher->qq}}</td>
        </tr>
    </table>

@stop

@section('js')
    <script>
        layui.use(['form', 'layer'],
            function () {
                var $ = layui.jquery,
                    form = layui.form,
                    layer = layui.layer;

                //监听提交
                form.on('submit(save)',
                    function (data) {
                        $.ajax({
                            type: 'put',
                            url: '{{route('teacher.update',$teacher->id)}}',
                            data: data.field,
                            success: function (res) {
                                my.msg(res);
                            }
                        });
                        return false;
                    });
            });
    </script>
@stop