routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// 需要登录
// 这里部分用数组的写法,因为,数组的写法比@的写法有个好处是,ide可以识别到,可以点击直接跳转到对应方法
Route::middleware('auth')->group(
    function () {
        // 权限相关
//        Route::get('/per/create', [\App\Http\Controllers\PermissionController::class, 'create']);
//        Route::get('/per/index', [\App\Http\Controllers\PermissionController::class, 'index']);
        // 初始化
        Route::get('/init', [\App\Http\Controllers\InitController::class, 'systemInit'])->name('init');
        Route::get('/clear', [\App\Http\Controllers\InitController::class, 'clear'])->name('clear');
        //首页
        Route::get('/', [\App\Http\Controllers\IndexController::class, 'index'])->name('index');
        Route::get('/welcome', [\App\Http\Controllers\IndexController::class, 'welcome'])->name('welcome');
        Route::get('/logout', [\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');

        // 个人信息
        Route::get('/info', [\App\Http\Controllers\UserController::class, 'info'])->name('user.info');
        // 学生
        Route::resource('/user', 'UserController');
        Route::post('/getuser', 'UserController@getUser')->name('getuser');
        Route::delete('/delall', 'UserController@deleteAll')->name('user.delall');
        Route::delete('/delparent/{id}', 'UserController@delParent')->name('user.delparent');
        Route::get('/export/user', 'UserController@export')->name('user.export');
        // 老师
        Route::resource('/teacher', 'TeacherController');
        Route::post('/getteacher', 'TeacherController@getTeacher')->name('getteacher');

        // 修改密码
        Route::get('/repwd', 'LoginController@showRepwdForm')->name('repwd');
        Route::post('/repwd', 'LoginController@repwd')->name('dorepwd');

        // 课程
        Route::resource('/course', 'CoursesController');
        Route::post('/getcourse', 'CoursesController@getcourse')->name('getcourse');

        // 考试
        Route::resource('/exam', 'ExamsController');
        Route::post('/getexams', 'ExamsController@getexams')->name('getexams');

        // 成绩
        Route::resource('/score', 'ScoresController');
        Route::post('/getscore', 'ScoresController@getscore')->name('getscore');
        Route::get('/export/score', 'ScoresController@export')->name('score.export');
        Route::post('/getfull', 'ScoresController@getFull')->name('score.getfull');

        // 成绩分析
        Route::get('/analyze/index', 'ScoreAnalyzeController@index')->name('analyze.index');
        Route::get('/analyze/pie/{cid}/{eid}', 'ScoreAnalyzeController@getPie')->name('analyze.getpie');
        Route::post('/analyze/showall', 'ScoreAnalyzeController@showAll')->name('analyze.showall');
        Route::post('/analyze/tips', 'ScoreAnalyzeController@tips')->name('analyze.tips');
        // 获取个人成绩不同考试折线图
        Route::post('/analyze/getrank', 'ScoreAnalyzeController@getRank')->name('analyze.getrank');
        // 个人分析列表页
        Route::get('/analyze/gerenfx', 'ScoreAnalyzeController@gerenfx')->name('analyze.gerenfx');
        Route::post('/analyze/hasscore', 'ScoreAnalyzeController@getHasScoreUser')->name('analyze.hasscore');

        // 管理员专属
        Route::resource('/admin', 'AdminController');
        Route::post('/admin.data', 'AdminController@getData')->name('admin.data');
    }
);


// 不需要登录
Route::middleware('guest')->group(
    function () {
        Route::get('/login', 'LoginController@index')->name('login');
        Route::post('/dologin', 'LoginController@store')->name('login.store');
    }
);

Route::any('/test', 'TestController@test')->name('test');

resources/views/admin/create.blade.php
@extends('common.layout')

@section('content')
    <form class="layui-form layuimini-form">
        <div class="layui-form-item">
            <label class="layui-form-label required">用户名</label>
            <div class="layui-input-inline">
                <input type="text" name="username" lay-verify="required" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label required">姓名</label>
            <div class="layui-input-inline">
                <input type="text" name="name" lay-verify="required" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label required">密码</label>
            <div class="layui-input-inline">
                <input type="text" name="password" lay-verify="required" class="layui-input">
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label required">角色</label>
            <div class="layui-input-inline">
                <select name="role_id" lay-verify="required" lay-search="" lay-filter="select_role">
                    <option value=""></option>
                    @foreach($roles as $v)
                        <option value="{{$v->id}}">{{$v->nickname}}</option>
                    @endforeach
                </select>
            </div>
        </div>


        <div class="layui-form-item" id="students" style="display: none;">
            <label class="layui-form-label">绑定学生</label>
            <div class="layui-input-inline">
                <select name="bind_student_id" lay-search="">
                    <option value=""></option>
                    @foreach($students as $v)
                        <option value="{{$v->id}}">{{$v->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="layui-form-item" id="teachers" style="display: none;">
            <label class="layui-form-label">绑定老师</label>
            <div class="layui-input-inline">
                <select name="bind_teacher_id" lay-search="">
                    <option value=""></option>
                    @foreach($teachers as $v)
                        <option value="{{$v->id}}">{{$v->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="layui-form-item" style="text-align: center;">
            <button class="layui-btn layui-btn-normal" lay-filter="save" lay-submit="">添 加</button>
        </div>
    </form>
@stop

@section('js')
    <script>
        layui.use(['form', 'layer'],
            function () {
                var $ = layui.jquery,
                    form = layui.form,
                    layer = layui.layer;

                form.on('select(select_role)', function(data){
                    var role = $(data.elem[data.value]).text();
                    if (role === '学生'){
                        $("#students").show();
                        $("#teachers").hide();
                    }else {
                        $("#students").hide();
                        $("#teachers").show();
                    }
                    form.render();
                });


                //监听提交
                form.on('submit(save)',
                    function (data) {
                        $.post('{{route('admin.store')}}', data.field, function (res) {
                            my.msg(res);
                        });
                        return false;
                    });
            });
    </script>
@stop

resources/views/admin/edit.blade.php
@extends('common.layout')

@section('content')
    <form class="layui-form layuimini-form" lay-filter="user">
        <div class="layui-form-item">
            <label class="layui-form-label required">用户名</label>
            <div class="layui-input-inline">
                <input type="text" name="username" lay-verify="required" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label required">姓名</label>
            <div class="layui-input-inline">
                <input type="text" name="name" lay-verify="required" class="layui-input">
            </div>
        </div>

        <div class="layui-form-item">
            <label class="layui-form-label">重置密码</label>
            <div class="layui-input-inline">
                <input type="text" name="password" class="layui-input">
            </div>
        </div>


        <div class="layui-form-item">
            <label class="layui-form-label required">角色</label>
            <div class="layui-input-inline">
                <select name="role_id" lay-verify="required" lay-search="" lay-filter="select_role">
                    <option value=""></option>
                    @foreach($roles as $v)
                        <option value="{{$v->id}}">{{$v->nickname}}</option>
                    @endforeach
                </select>
            </div>
        </div>


        <div class="layui-form-item" id="students" style="display: none;">
            <label class="layui-form-label">绑定学生</label>
            <div class="layui-input-inline">
                <select name="bind_student_id" lay-search="">
                    <option value=""></option>
                    @foreach($students as $v)
                        <option value="{{$v->id}}">{{$v->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="layui-form-item" id="teachers" style="display: none;">
            <label class="layui-form-label">绑定老师</label>
            <div class="layui-input-inline">
                <select name="bind_teacher_id" lay-search="">
                    <option value=""></option>
                    @foreach($teachers as $v)
                        <option value="{{$v->id}}">{{$v->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="layui-form-item" style="text-align: center;">
            <button class="layui-btn layui-btn-normal" lay-filter="save" lay-submit="">修  改</button>
        </div>
    </form>
@stop

@section('js')
    <script>
        layui.use(['form', 'layer'],
            function () {
                var $ = layui.jquery,
                    form = layui.form,
                    layer = layui.layer;

                var data = @json($user)

                form.val('user', data);
                form.render();
                if (data.role_id === 3){
                    // 学生,显示绑定学生
                    $("#students").show();
                    $("#teachers").hide();
                }else {
                    $("#students").hide();
                    $("#teachers").show();
                }

                form.on('select(select_role)', function(data){
                    var role = $(data.elem[data.value]).text();
                    if (role === '学生'){
                        $("#students").show();
                        $("#teachers").hide();
                    }else {
                        $("#students").hide();
                        $("#teachers").show();
                    }
                    form.render();
                });


                //监听提交
                form.on('submit(save)',
                    function (data) {

                        $.ajax({
                            type: 'put',
                            url: '{{route('admin.update',$user->id)}}',
                            data: data.field,
                            success: function (res) {
                                my.msg(res);
                            }
                        });
                        return false;
                    });
            });
    </script>
@stop

resources/views/admin/index.blade.php
@extends('common.layout')

@section('content')
    <table id="adin_table" lay-filter="test"></table>
@stop

@section('js')
    @include('common.addbtn',['name'=>'添加'])
    @include('common.operation')

    <script>
        layui.use(['laydate', 'table'],
            function () {
                var $ = layui.jquery,
                    table = layui.table
                    , laydate = layui.laydate;


                table.render({
                    elem: '#adin_table'
                    , height: 'full-130'
                    , method: 'post'
                    , url: '{{route('admin.data')}}' //数据接口
                    , page: true //开启分页
                    , cellMinWidth: 50 //全局定义常规单元格的最小宽度
                    , cols: [[ //表头
                        {type: 'numbers', title: '序号', width: 100, align: 'center'}
                        , {field: 'username', title: '用户名', sort: true, align: 'center'}
                        , {field: 'name', title: '昵称', sort: true, align: 'center'}
                        , {field: 'role', title: '角色', sort: true, align: 'center'}
                        , {field: 'bind_username', title: '绑定的用户名', sort: true, align: 'center'}

                        @can('isAdmin')
                        , {title: '操作', toolbar: '#barDemo', width: 150}
                        @endcan
                    ]]
                    , limit: 10
                    , limits: [10, 20, 30, 50, 100]
                    , toolbar: '#toolbarDemo'
                });

                //监听行工具事件
                table.on('tool(test)', function (obj) {
                    var data = obj.data;
                    switch (obj.event) {
                        //监听单元格事件
                        case 'edit':
                            var url = '{{route('admin.edit','xxx')}}'.replace('xxx', data.id);
                            my.open('修改用户信息', url, 60, 80);
                            break;

                        case 'del':
                            layer.confirm('真的删除用户<span style="color:red;">' + data.name + '</span>么', function (index) {
                                var url = '{{route('admin.destroy','xxx')}}'.replace('xxx', data.id);
                                $.ajax({
                                    type: 'delete',
                                    url: url,
                                    success: function (res) {
                                        my.msg(res);
                                    }
                                });

                            });
                            break;
                    }
                });

                //头工具栏事件
                table.on('toolbar(test)', function (obj) {
                    var data = obj.data;
                    switch (obj.event) {
                        case 'add':
                            my.open('添加用户', '{{route('admin.create')}}', 50);
                            break;
                    }
                });
            });
    </script>
@stop