routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// 需要登录
// 这里部分用数组的写法,因为,数组的写法比@的写法有个好处是,ide可以识别到,可以点击直接跳转到对应方法
Route::middleware('auth')->group(
    function () {
        // 权限相关
//        Route::get('/per/create', [\App\Http\Controllers\PermissionController::class, 'create']);
//        Route::get('/per/index', [\App\Http\Controllers\PermissionController::class, 'index']);
        // 初始化
        Route::get('/init', [\App\Http\Controllers\InitController::class, 'systemInit'])->name('init');
        Route::get('/clear', [\App\Http\Controllers\InitController::class, 'clear'])->name('clear');
        //首页
        Route::get('/', [\App\Http\Controllers\IndexController::class, 'index'])->name('index');
        Route::get('/welcome', [\App\Http\Controllers\IndexController::class, 'welcome'])->name('welcome');
        Route::get('/logout', [\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');

        // 个人信息
        Route::get('/info', [\App\Http\Controllers\UserController::class, 'info'])->name('user.info');
        // 学生
        Route::resource('/user', 'UserController');
        Route::post('/getuser', 'UserController@getUser')->name('getuser');
        Route::delete('/delall', 'UserController@deleteAll')->name('user.delall');
        Route::delete('/delparent/{id}', 'UserController@delParent')->name('user.delparent');
        Route::get('/export/user', 'UserController@export')->name('user.export');
        // 老师
        Route::resource('/teacher', 'TeacherController');
        Route::post('/getteacher', 'TeacherController@getTeacher')->name('getteacher');

        // 修改密码
        Route::get('/repwd', 'LoginController@showRepwdForm')->name('repwd');
        Route::post('/repwd', 'LoginController@repwd')->name('dorepwd');

        // 课程
        Route::resource('/course', 'CoursesController');
        Route::post('/getcourse', 'CoursesController@getcourse')->name('getcourse');

        // 考试
        Route::resource('/exam', 'ExamsController');
        Route::post('/getexams', 'ExamsController@getexams')->name('getexams');

        // 成绩
        Route::resource('/score', 'ScoresController');
        Route::post('/getscore', 'ScoresController@getscore')->name('getscore');
        Route::get('/export/score', 'ScoresController@export')->name('score.export');
        Route::post('/getfull', 'ScoresController@getFull')->name('score.getfull');

        // 成绩分析
        Route::get('/analyze/index', 'ScoreAnalyzeController@index')->name('analyze.index');
        Route::get('/analyze/pie/{cid}/{eid}', 'ScoreAnalyzeController@getPie')->name('analyze.getpie');
        Route::post('/analyze/showall', 'ScoreAnalyzeController@showAll')->name('analyze.showall');
        Route::post('/analyze/tips', 'ScoreAnalyzeController@tips')->name('analyze.tips');
        // 获取个人成绩不同考试折线图
        Route::post('/analyze/getrank', 'ScoreAnalyzeController@getRank')->name('analyze.getrank');
        // 个人分析列表页
        Route::get('/analyze/gerenfx', 'ScoreAnalyzeController@gerenfx')->name('analyze.gerenfx');
        Route::post('/analyze/hasscore', 'ScoreAnalyzeController@getHasScoreUser')->name('analyze.hasscore');

        // 管理员专属
        Route::resource('/admin', 'AdminController');
        Route::post('/admin.data', 'AdminController@getData')->name('admin.data');
    }
);


// 不需要登录
Route::middleware('guest')->group(
    function () {
        Route::get('/login', 'LoginController@index')->name('login');
        Route::post('/dologin', 'LoginController@store')->name('login.store');
    }
);

Route::any('/test', 'TestController@test')->name('test');

app/Http/Controllers/ExamsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Models\ExamsModel;

class ExamsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('exams.index');
    }

    public function getexams(Request $request)
    {
        $page = $request->input('page');
        $limit = $request->input('limit');
        $offset = ($page - 1) * $limit;
        $data = ExamsModel::orderBy('time')->offset($offset)->paginate($limit)->toArray();
        $res['data'] = $data['data'];
        $res['code'] = 0;
        $res['count'] = $data['total'];
        $res['msg'] = '获取数据失败';

        return $res;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $exams = ExamsModel::orderBy('time')->get();

        return view('exams.create', compact('exams'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $res = ExamsModel::create($request->all());
        if ($res) {
            return $this->success('添加成功');
        } else {
            return $this->fail('添加失败');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $exam = ExamsModel::find($id);
        if (Gate::denies('isAdmin')) {
            return view('user.noper');
        }

        return view('exams.edit', compact('exam'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $exam = ExamsModel::find($id);

        if (Gate::denies('isAdmin')) {
            return $this->fail('您无权修改考试');
        }
        $res = $exam->update($request->all());
        if ($res) {
            return $this->success('修改成功');
        } else {
            return $this->fail('修改失败');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Gate::denies('isAdmin')) {
            return $this->fail('您无权删除考试');
        }
        $res = ExamsModel::destroy($id);
        if ($res) {
            return $this->success('删除成功');
        }

        return $this->fail('删除失败');
    }
}

resources/views/exams/create.blade.php
@extends('common.layout')

@section('content')
    <form class="layui-form layuimini-form">
        <div class="layui-form-item">
            <label class="layui-form-label">考试名称</label>
            <div class="layui-input-inline">
                <input type="text" name="name" class="layui-input" lay-verify="required">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">考试时间</label>
            <div class="layui-input-inline">
                <input id="time" class="layui-input" name="time" type="text" autocomplete="off">
            </div>
        </div>
        <div class="layui-form-item" style="text-align: center;">
            <button class="layui-btn" lay-filter="save" lay-submit="">提交</button>
        </div>
    </form>
@stop

@section('js')
    <script>
        layui.use(['laydate', 'form', 'layer'],
            function () {
                var $ = layui.jquery,
                    form = layui.form,
                    laydate = layui.laydate;

                laydate.render({
                    elem: '#time', //指定元素
                    trigger: 'click'
                });
                //监听提交
                form.on('submit(save)',
                    function (data) {
                        $.post('{{route('exam.store')}}', data.field, function (res) {
                            my.msg(res);
                        });
                        return false;
                    });
            });
    </script>
@stop

resources/views/exams/edit.blade.php
@extends('common.layout')

@section('content')
    <form class="layui-form layuimini-form" lay-filter="exam">
        <div class="layui-form-item">
            <label class="layui-form-label">考试名称</label>
            <div class="layui-input-inline">
                <input type="text" name="name" class="layui-input" lay-verify="required">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">考试时间</label>
            <div class="layui-input-inline">
                <input autocomplete="off" id="time" class="layui-input" name="time" type="text">
            </div>
        </div>
        <div class="layui-form-item" style="text-align: center;">
            <button class="layui-btn" lay-filter="save" lay-submit="">提交</button>
        </div>
    </form>
@stop

@section('js')
    <script>
        layui.use(['laydate', 'form', 'layer'],
            function () {
                var $ = layui.jquery,
                    form = layui.form,
                    laydate = layui.laydate,
                    layer = layui.layer;

                laydate.render({
                    elem: '#time', //指定元素
                    trigger: 'click'
                });
                form.val('exam', @json($exam));
                //监听提交
                form.on('submit(save)',
                    function (data) {
                        $.ajax({
                            type: 'put',
                            url: '{{route('exam.update',$exam->id)}}',
                            data: data.field,
                            success: function (res) {
                                my.msg(res);
                            }
                        });
                        return false;
                    });
            });
    </script>
@stop

resources/views/exams/index.blade.php
@extends('common.layout')

@section('content')
    <table id="exam_table" lay-filter="test"></table>
@stop

@section('js')
    @include('common.addbtn',['name'=>'添加'])
    @include('common.operation')

    <script>
        layui.use(['laydate', 'table'],
            function () {
                var $ = layui.jquery,
                    table = layui.table,
                    laydate = layui.laydate;
                //执行一个laydate实例
                laydate.render({
                    elem: '#start' //指定元素
                    , trigger: 'click'
                });
                //执行一个laydate实例
                laydate.render({
                    elem: '#end' //指定元素
                    , trigger: 'click'
                });

                table.render({
                    elem: '#exam_table'
                    , height: 'full-130'
                    , method: 'post'
                    , url: '{{route('getexams')}}' //数据接口
                    , page: true //开启分页
                    , cellMinWidth: 50 //全局定义常规单元格的最小宽度
                    , cols: [[
                        {type: 'numbers', title: '序号', width: 100, align: 'center'}
                        , {field: 'name', title: '考试名称', sort: true, align: 'center'}
                        , {field: 'time', title: '考试时间', sort: true, align: 'center'}
                        @can('isAdmin')
                        , {title: '操作', toolbar: '#barDemo', width: 150}
                        @endcan
                    ]]
                    , limit: 10
                    , limits: [10, 20, 30, 50, 100]
                    , toolbar: '#toolbarDemo'
                });

                //监听行工具事件
                table.on('tool(test)', function (obj) {
                    var data = obj.data;
                    switch (obj.event) {
                        case 'edit':
                            var url = '{{route('exam.edit','xxx')}}'.replace('xxx', data.id);
                            my.open('修改考试信息', url, 40, 50);
                            break;

                        case 'del':
                            layer.confirm('真的删除<span style="color:red;">' + data.name + '</span>考试么', function (index) {
                                var url = '{{route('exam.destroy','xxx')}}'.replace('xxx', data.id);
                                $.ajax({
                                    type: 'delete',
                                    url: url,
                                    success: function (res) {
                                        my.msg(res);
                                    }
                                });

                            });
                            break;
                    }
                });

                //头工具栏事件
                table.on('toolbar(test)', function (obj) {
                    switch (obj.event) {
                        case 'add':
                            my.open('添加考试', '{{route('exam.create')}}', 40);
                            break;
                    }
                });

                @can('isAdmin')
                //监听行双击事件（双击事件为：row）
                table.on('rowDouble(test)', function (obj) {
                    var data = obj.data;
                    // 在这里显示某个学生具体的弹窗
                    var url = '{{route('exam.edit','xxx')}}'.replace('xxx', data.id);
                    my.open('修改考试信息', url, 40, 50);
                    //标注选中样式
                    obj.tr.addClass('layui-table-click').siblings().removeClass('layui-table-click');
                });
                @endcan
            });
    </script>
@stop