routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// 需要登录
// 这里部分用数组的写法,因为,数组的写法比@的写法有个好处是,ide可以识别到,可以点击直接跳转到对应方法
Route::middleware('auth')->group(
    function () {
        // 权限相关
//        Route::get('/per/create', [\App\Http\Controllers\PermissionController::class, 'create']);
//        Route::get('/per/index', [\App\Http\Controllers\PermissionController::class, 'index']);
        // 初始化
        Route::get('/init', [\App\Http\Controllers\InitController::class, 'systemInit'])->name('init');
        Route::get('/clear', [\App\Http\Controllers\InitController::class, 'clear'])->name('clear');
        //首页
        Route::get('/', [\App\Http\Controllers\IndexController::class, 'index'])->name('index');
        Route::get('/welcome', [\App\Http\Controllers\IndexController::class, 'welcome'])->name('welcome');
        Route::get('/logout', [\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');

        // 个人信息
        Route::get('/info', [\App\Http\Controllers\UserController::class, 'info'])->name('user.info');
        // 学生
        Route::resource('/user', 'UserController');
        Route::post('/getuser', 'UserController@getUser')->name('getuser');
        Route::delete('/delall', 'UserController@deleteAll')->name('user.delall');
        Route::delete('/delparent/{id}', 'UserController@delParent')->name('user.delparent');
        Route::get('/export/user', 'UserController@export')->name('user.export');
        // 老师
        Route::resource('/teacher', 'TeacherController');
        Route::post('/getteacher', 'TeacherController@getTeacher')->name('getteacher');

        // 修改密码
        Route::get('/repwd', 'LoginController@showRepwdForm')->name('repwd');
        Route::post('/repwd', 'LoginController@repwd')->name('dorepwd');

        // 课程
        Route::resource('/course', 'CoursesController');
        Route::post('/getcourse', 'CoursesController@getcourse')->name('getcourse');

        // 考试
        Route::resource('/exam', 'ExamsController');
        Route::post('/getexams', 'ExamsController@getexams')->name('getexams');

        // 成绩
        Route::resource('/score', 'ScoresController');
        Route::post('/getscore', 'ScoresController@getscore')->name('getscore');
        Route::get('/export/score', 'ScoresController@export')->name('score.export');
        Route::post('/getfull', 'ScoresController@getFull')->name('score.getfull');

        // 成绩分析
        Route::get('/analyze/index', 'ScoreAnalyzeController@index')->name('analyze.index');
        Route::get('/analyze/pie/{cid}/{eid}', 'ScoreAnalyzeController@getPie')->name('analyze.getpie');
        Route::post('/analyze/showall', 'ScoreAnalyzeController@showAll')->name('analyze.showall');
        Route::post('/analyze/tips', 'ScoreAnalyzeController@tips')->name('analyze.tips');
        // 获取个人成绩不同考试折线图
        Route::post('/analyze/getrank', 'ScoreAnalyzeController@getRank')->name('analyze.getrank');
        // 个人分析列表页
        Route::get('/analyze/gerenfx', 'ScoreAnalyzeController@gerenfx')->name('analyze.gerenfx');
        Route::post('/analyze/hasscore', 'ScoreAnalyzeController@getHasScoreUser')->name('analyze.hasscore');

        // 管理员专属
        Route::resource('/admin', 'AdminController');
        Route::post('/admin.data', 'AdminController@getData')->name('admin.data');
    }
);


// 不需要登录
Route::middleware('guest')->group(
    function () {
        Route::get('/login', 'LoginController@index')->name('login');
        Route::post('/dologin', 'LoginController@store')->name('login.store');
    }
);

Route::any('/test', 'TestController@test')->name('test');

app/Http/Controllers/CoursesController.php
<?php

namespace App\Http\Controllers;

use App\Models\CoursesModel;
use App\Models\TeachersModel;
use Illuminate\Http\Request;
use Gate;

class CoursesController extends Controller
{
    public function __construct()
    {
        // 规定只有老师才能访问的方法
        $this->middleware(['role:teacher'])->only(['store', 'create', 'destroy', 'edit','update']);
    }

    public function index()
    {
        return view('courses.index');
    }

    public function getcourse(Request $request)
    {
        $page = $request->input('page');
        $limit = $request->input('limit');
        $offset = ($page - 1) * $limit;
        $data = CoursesModel::with('teacher')->offset($offset)->paginate($limit)->toArray();
        $res['data'] = $data['data'];
        $res['code'] = 0;
        $res['count'] = $data['total'];
        $res['msg'] = '获取数据失败';

        return $res;
    }


    public function create()
    {
        $teachers = TeachersModel::get();

        return view('courses.create', compact('teachers'));
    }


    public function store(Request $request)
    {
        $res = CoursesModel::create($request->all());
        if ($res) {
            return $this->success('添加成功');
        } else {
            return $this->fail('添加失败');
        }
    }


    public function edit($id)
    {
        $course = CoursesModel::find($id);
        $teachers = TeachersModel::get();

        return view('courses.edit', compact('course', 'teachers'));
    }


    public function update(Request $request, $id)
    {
        $course = CoursesModel::find($id);

        $res = $course->update($request->all());
        if ($res) {
            return $this->success('修改成功');
        } else {
            return $this->fail('修改失败');
        }
    }


    public function destroy($id)
    {

        $res = CoursesModel::destroy($id);
        if ($res) {
            return $this->success('删除成功');
        }

        return $this->fail('删除失败');
    }
}

resources/views/courses/create.blade.php
@extends('common.layout')

@section('content')
    <form class="layui-form layuimini-form">
        <div class="layui-form-item">
            <label class="layui-form-label required">课程名称</label>
            <div class="layui-input-inline">
                <input type="text" name="name" lay-verify="required" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">满分</label>
            <div class="layui-input-inline">
                <input type="text" name="full" class="layui-input" lay-verify="required">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label required">授课老师</label>
            <div class="layui-input-inline">
                <select name="teacher_id" lay-verify="required" lay-search="">
                    <option value=""></option>
                    @foreach($teachers as $v)
                        <option value="{{$v->id}}">{{$v->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="layui-form-item" style="text-align: center;">
            <button class="layui-btn" lay-filter="save" lay-submit="">提交</button>
        </div>
    </form>
@stop

@section('js')
    <script>
        layui.use(['form', 'layer'],
            function () {
                var $ = layui.jquery,
                    form = layui.form,
                    layer = layui.layer;

                //监听提交
                form.on('submit(save)',
                    function (data) {
                        $.post('{{route('course.store')}}', data.field, function (res) {
                            my.msg(res);
                        });
                        return false;
                    });
            });
    </script>
@stop

resources/views/courses/edit.blade.php
@extends('common.layout')

@section('content')
    <form class="layui-form layuimini-form" lay-filter="course">
        <div class="layui-form-item">
            <label class="layui-form-label required">课程名称</label>
            <div class="layui-input-inline">
                <input type="text" name="name" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">满分</label>
            <div class="layui-input-inline">
                <input type="text" name="full" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label required">授课老师</label>
            <div class="layui-input-inline">
                <select name="teacher_id">
                    <option value=""></option>
                    @foreach($teachers as $v)
                        <option value="{{$v->id}}">{{$v->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="layui-form-item" style="text-align: center;">
            <button class="layui-btn" lay-filter="save" lay-submit="">提交</button>
        </div>
    </form>
@stop

@section('js')
    <script>
        layui.use(['form', 'layer'],
            function () {
                var $ = layui.jquery,
                    form = layui.form,
                    layer = layui.layer;

                form.val('course', @json($course));
                //监听提交
                form.on('submit(save)',
                    function (data) {
                        $.ajax({
                            type: 'put',
                            url: '{{route('course.update',$course->id)}}',
                            data: data.field,
                            success: function (res) {
                                my.msg(res);
                            }
                        });
                        return false;
                    });
            });
    </script>
@stop

resources/views/courses/index.blade.php
@extends('common.layout')

@section('content')
    <table id="course_table" lay-filter="test"></table>
@stop

@section('js')
    @include('common.addbtn',['name'=>'添加'])
    @include('common.operation')

    <script>
        layui.use(['laydate', 'table'],
            function () {
                var $ = layui.jquery,
                    table = layui.table
                    , laydate = layui.laydate;

                laydate.render({
                    elem: '#start' //指定元素
                    , trigger: 'click'
                });

                laydate.render({
                    elem: '#end' //指定元素
                    , trigger: 'click'
                });

                table.render({
                    elem: '#course_table'
                    , height: 'full-130'
                    , method: 'post'
                    , url: '{{route('getcourse')}}' //数据接口
                    , page: true //开启分页
                    , cellMinWidth: 50 //全局定义常规单元格的最小宽度
                    , cols: [[ //表头
                        {field: 'teacher_id', hide: true}
                        , {type: 'numbers', title: '序号', width: 100, align: 'center'}
                        , {field: 'name', title: '课程名称', sort: true, align: 'center'}
                        , {field: 'full', title: '满分', sort: true, align: 'center'}
                        , {
                            field: 'teacher',
                            event: 'show_teacher',
                            title: '授课老师',
                            sort: true,
                            align: 'center',
                            templet: function (d) {
                                if (!d.teacher) {
                                    return '<span style="cursor: pointer;" class="layui-badge">未指定老师</span>';
                                }
                                return '<span style="cursor: pointer;" class="layui-badge layui-bg-blue">' + d.teacher.name + '</span>';
                            }
                        }
                        @can('isAdmin')
                        , {title: '操作', toolbar: '#barDemo', width: 150}
                        @endcan
                    ]]
                    , limit: 10
                    , limits: [10, 20, 30, 50, 100]
                    , toolbar: '#toolbarDemo'
                });

                //监听行工具事件
                table.on('tool(test)', function (obj) {
                    var data = obj.data;
                    switch (obj.event) {
                        //监听单元格事件
                        case 'show_teacher':
                            if (data.teacher) {
                                var url = '{{route('teacher.show','xxx')}}'.replace('xxx', data.teacher_id);
                                my.open('授课老师信息', url, 40);
                            } else {
                                layer.alert('该课程未指定老师,请让管理员双击指定授课老师!', {icon: 5})
                            }
                            break;
                        case 'edit':
                            var url = '{{route('course.edit','xxx')}}'.replace('xxx', data.id);
                            my.open('修改课程信息', url, 40, 50);
                            break;

                        case 'del':
                            layer.confirm('真的删除<span style="color:red;">' + data.name + '</span>课程么', function (index) {
                                var url = '{{route('course.destroy','xxx')}}'.replace('xxx', data.id);
                                $.ajax({
                                    type: 'delete',
                                    url: url,
                                    success: function (res) {
                                        my.msg(res);
                                    }
                                });

                            });
                            break;
                    }

                });

                //头工具栏事件
                table.on('toolbar(test)', function (obj) {
                    var data = obj.data;

                    switch (obj.event) {
                        case 'add':
                            my.open('添加课程', '{{route('course.create')}}', 50);
                            break;
                    }
                    ;
                });

                @can('isAdmin')
                //监听行双击事件（双击事件为：row）
                table.on('rowDouble(test)', function (obj) {
                    var data = obj.data;
                    // 在这里显示某个学生具体的弹窗
                    var url = '{{route('course.edit','xxx')}}'.replace('xxx', data.id);
                    my.open('修改课程信息', url, 40, 50);
                    //标注选中样式
                    obj.tr.addClass('layui-table-click').siblings().removeClass('layui-table-click');
                });
                @endcan
            });
    </script>
@stop